package org.example.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Data Transfer Object for payment requests.
 * Sent from Gateway to Switch to initiate a transaction.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentRequest {

    /**
     * Unique transaction ID (generated by Switch).
     * Used for idempotency checks and tracking.
     */
    private String txnId;

    /**
     * Amount to transfer.
     * e.g., 500.00
     */
    private BigDecimal amount;

    /**
     * Sender's Virtual Payment Address.
     * e.g., "alice@l0"
     */
    private String payerVpa;

    /**
     * Receiver's Virtual Payment Address.
     * e.g., "bob@l0"
     */
    private String payeeVpa;

    /**
     * Hashed MPIN (SHA-256).
     * Gateway hashes the raw PIN before sending.
     */
    private String mpinHash;

    /**
     * Fraud detection metadata.
     * Collected by Gateway for ML risk scoring.
     */
    private FraudCheckData fraudCheckData;
}